#!/bin/bash

echo ""
echo "This script runs 'sudo chmod 666 /dev/spidev0.0 /dev/spidev0.1' "
echo "to facilitate bringing up the STOB CANBUS connection."
echo ""

sudo chmod 666 /dev/spidev0.0 /dev/spidev0.1

echo ""
echo "Ready!"
echo ""